on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup mochi-thallium
      run: |
        git clone https://github.com/spack/spack.git src/spack
        . src/spack/share/spack/setup-env.sh
        git clone https://xgitlab.cels.anl.gov/sds/sds-repo.git src/sds-repo
        spack repo add src/sds-repo
        . ./setup_packages.sh 
        spack install mochi-thallium
    - name: Build
      run: |
        . src/spack/share/spack/setup-env.sh
        spack load -r mochi-thallium
        spack find -dlv mochi-thallium
        make
    - name: Install assert.sh 
      run: |
        wget https://raw.github.com/lehmannro/assert.sh/v1.1/assert.sh
    - name: Run server 
      run: |
        . src/spack/share/spack/setup-env.sh
        spack load -r mochi-thallium
        ./server > log &
    - name: Test1 # 最初はFollower
      run: |
        . assert.sh
        cat log | grep "\[follower\] become"
        assert_raises `echo $?`
        cat log | grep "\[follower\] candidate"
        assert_raises `echo $?` 1
    - name: Test2 # 3秒後にCandidateになる
      run: |
        sleep 3 
        . assert.sh
        cat log | grep "\[follower\] become"
        assert_raises `echo $?`
        cat log | grep "\[follower\] candidate"
        assert_raises `echo $?`


